services:
  - type: web
    name: statscout-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ODDS_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
